### ISSUE TITLE
DarkenedUI Option resets DPSMate settings

### ISSUE THREAD

**Issue by Sorin-M-Oprea** [shagu/ShaguTweaks#10]
Running pfUI, ShaguTweaks and DPSMate. All the latest versions as of today.

When selecting the option `DarkenedUI` from ShaguTweaks, I see that DPSMate settings get reset completely to defaults.

![Clipboard Image (Large)](https://user-images.githubusercontent.com/45243695/149334076-1a473912-1fff-4dd6-ad1d-9de80ef3e7ce.png)

Not sure how to help further with this.

**Comment by shagu** [comment]
Telling you the same as on discord:

> Disable Thirdparty -> Integrations -> DPSMate (Skin) and DPSMate (Dock)
If you wish to have pfUI not touch the DPSMate settings (style, position, etc).

While the integration is active, it sets the DPSMate colors to match the pfUI colors and moves it into the dock.
Having the DPSMate integration of pfUI disabled, nothing resets on my end when using all 3 addons.

**Comment by Sorin-M-Oprea** [comment]
I still want to have it docked though.

**Comment by Sorin-M-Oprea** [comment]
Please see this video capture. As soon as I do a /rl it goes back. The only time when this does not happen is if I disable Darkened UI from ShaguTweaks addon. That module somehow interferes with it. Is it possible to exclude DPSMate from the Darkened UI option?
https://user-images.githubusercontent.com/45243695/149400531-a724f224-905e-4bc5-8b72-991aecec525b.mp4

**Comment by Sorin-M-Oprea** [comment]
![image](https://user-images.githubusercontent.com/45243695/149404467-c20cd759-649d-4a54-9d78-3ab5ebb301be.png)

Nevermind, I fixed it myself by adding those first 2 lines inside Shagu-Tweaks Darkened UI module file as well as the below settings for my use case in pfUI.

![image](https://user-images.githubusercontent.com/45243695/149404675-46be234b-e685-4ff8-bc59-20b8e32c7575.png)
