### ISSUE TITLE
ShaguTweaks not working without Gatherer (no dependancy information shown in the lobby either)

### ISSUE THREAD

**Issue by Aurigon** [shagu/ShaguTweaks#11]
On 1.12.1 clients, ShaguTweaks stops working (and displays many LUA errors) if one doesn't have the p2p version of the Gatherer addon installed as well (the one which synchs nodes through guild chat). The ShaguTweak option window is empty (only bottom buttons are displayed). See the following screen for details:

![Immagine](https://user-images.githubusercontent.com/2293227/154686479-88a7c18c-503b-4456-9c34-d0412d0b7b20.png)

**Comment by shagu** [comment]
I can't reproduce your Issue. I never used Gatherer at all.
Please disable all other addons beside ShaguTweaks and enable them again one by one to see which one is breaking it.

**Comment by Aurigon** [comment]
For the sake of clarity, I found there was an addon (one I had coded for me for my own personal usage) that was conflicting with ShaguTweaks, as I disabled all addons, re-enabled them one by one, and the error only reappeared after I enabled this other addon. Still weird that everything works, unless I use an older version of Gatherer. Oh well.
