### ISSUE TITLE
Feature request: Wider Advanced Options Window

### ISSUE THREAD

**Issue by GryllsAddons** [shagu/ShaguTweaks#19]
Please could we have a wider "Advanced Options" window with an additional column to allow for more mods to fit. It would be great to be able to share small tweaks as additional mods however there is limited room available for this.

![shagutweaks](https://user-images.githubusercontent.com/107083057/187556500-824eb7be-e4e1-4b0e-bfd7-154d55fc9776.png)

**Comment by Mosch0512** [comment]
Having multiple Tabs would also be possible.

**Comment by shagu** [comment]
Done via https://github.com/shagu/ShaguTweaks/pull/33
