### ISSUE TITLE
HFQ junk sell error

### ISSUE THREAD

**Issue by burner1024** [shagu/ShaguTweaks#21]
This and some other junk from HFQ throw errors upon pressing sell junk button.
![Captura de pantalla de 2022-09-25 17-20-04](https://user-images.githubusercontent.com/1279852/192138707-f1de379e-2596-4457-9a8f-bbbc280337fc.png)

![Captura de pantalla de 2022-09-25 17-19-44](https://user-images.githubusercontent.com/1279852/192138669-77d35739-ca97-4ba8-b5d0-57742f94cffa.png)

**Comment by shagu** [comment]
Are you sure this happens on the latest version?
It should have been fixed 3 months ago:
https://github.com/shagu/ShaguTweaks/commit/c3e5cebc29cae4d5bf8980771e4da6a7ddaf2ed9

**Comment by burner1024** [comment]
Uhm, I'll recheck and report.

**Comment by burner1024** [comment]
My bad, I had older version.
