### ISSUE TITLE
Shift Click chat names function similar to PFUI

### ISSUE THREAD

**Issue by stburrus** [shagu/ShaguTweaks#22]
In PFUI you can shift click names in chat to paste their name, and, make it linkable with their class colors etc. As seen in the screenshot. However, in ShaguTweaks you can only shift click, but, it doesn't color them/make it clickable like it does in PFUI. I think this would be a nice addition to ShaguTweaks. 
![image](https://user-images.githubusercontent.com/86021808/196023576-5b824f91-b277-434b-9455-0f27414300e6.png)

**Comment by shagu** [comment]
https://github.com/shagu/ShaguTweaks/commit/5014a47bac39e25c3caee512b940298436049f9b
