### ISSUE TITLE
Party frames not colored

### ISSUE THREAD

**Issue by Volkyte** [shagu/ShaguTweaks#24]
Tweaks allow an oiption to colour party frames health bar by the color of their class. Since last 2 update, this never happens, even by redownloading addon and trying to relog. With option checked on and off, nothn changes.

![Immagine 2022-11-15 094157](https://user-images.githubusercontent.com/16918614/201877479-955f99b2-e533-4444-bda7-43d8d36437a7.jpg)

**Comment by shagu** [comment]
It never did that. The colors that are applied to the party frames are the names, not the healthbars.
