### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguTweaks#3]
ShaguTweaks is a great addon, replacing many other, small addons!

I would like to place the following feature requests:
* Coordinates - add cursor coordinates too
* The health text on enemy targets (Real Health Numbers) is not really visible (green ink on green background) - pretty please add an option to color it in white all the time
* More visible colors for Item rarity borders - ideally like [oGlow](https://github.com/crazypoultry/addons/tree/master/addons/O/oGlow_20130112-173944/oGlow). At this moment, the borders are very faint (to me) and hardly visible, very hard to make a difference between blue and purple
* Enemy Castbars - Play a sound when your target is casting a spell, like [Antagonist](https://legacy-wow.com/vanilla-addons/antagonist/) does

Would be awesome to add the functionality of these other small addons:
* <a href="https://legacy-wow.com/vanilla-addons/quickloot/">QuickLoot</a>
* <a href="https://github.com/gashole/DruidManaBar">DruidManaBar</a>
* <a href="https://github.com/wbb1977/ChatTimestamps">ChatTimestamps</a>
* <a href="https://github.com/Voidmenull/WhoList_Fix">WhoList_Fix</a>
* <a href="https://legacy-wow.com/vanilla-addons/corpse-info/">Corpse Info</a>
* <a href="https://github.com/shirsig/retarget">Retarget</a>
* <a href="https://github.com/shirsig/sentry">Sentry</a>
* <a href="https://github.com/anzz1/TopMeOff">TopMeOff</a> (or <a href="https://github.com/Shanghi/AutoShop">AutoShop</a> - this one is a bit too complex tho)
* [SpellAlert](https://github.com/Brqje/SpellAlert)

**Comment by FrostShock** [comment]
Sorry, I wasn't aware about the star button :)
Now I starred all the addons I am using or I was using.

Is there an easy way to change the source to add the oGlow borders?
I was using Antagonist and I found it very useful to hear a sound when the targeted enemy starts casting a spell. Where in the source should I add PlaySound("RaidWarning")?

As for including other addons, it's about including the functionality of those addons, not their source. If you ever find the time to make your own module for those features. 
WhoList_Fix is only 12 lines of code.
ChatTimestamps, CorpseInfo and DruidManaBar would be really cool to include, and they fit very well in the theme of ShaguTweaks.

Also it would be very nice to add an option to remove Gryphons:

MainMenuBarLeftEndCap:Hide();
MainMenuBarRightEndCap:Hide();

Those people who send you their addons, it would be cool if they would fork ShaguTweaks to add their addons.

**Comment by shagu** [comment]
> Also if possible, write them a bit more to the right, as the text "Coordinates" is covered by the Gatherer button "Hide".

The coordinates will now dodge the gatherer button: https://github.com/shagu/ShaguTweaks/commit/25ed258997b4317dc66c0729678249fe7f6e0f55

**Comment by shagu** [comment]
> Sorry to bother, how can I make it show the player coordinates too?

https://wowwiki-archive.fandom.com/wiki/API_GetPlayerMapPosition

> Another question: how can I make it show my own health and mana like 1000 / 3000 and 500 / 5000 ? (in my portrait)

https://wowwiki-archive.fandom.com/wiki/API_UnitHealth
https://wowwiki-archive.fandom.com/wiki/API_UnitMana
