### ISSUE TITLE
[TBC/2.4.3] Vendor value

### ISSUE THREAD

**Issue by maybedisp** [shagu/ShaguTweaks#30]
Some items don't show vendor value, and if you mouse over them, it will spam the chat with:
**...\Interface\Addons\ShaguTweaks-tbc\mods\vendor-values.lua:3881: attempt to compare number with string** errors
![WoWScrnShot_011923_215237](https://user-images.githubusercontent.com/114700006/213557859-f8b8c5ee-c221-4161-91e6-4a4a5fcf71d5.jpg)

**Comment by geojak** [comment]
Yea would be great if missing entries were catches instead of error.

**Comment by shagu** [comment]
Ooops! That shouldn't have happened. Thanks for reporting, it's fixed in the latest version by https://github.com/shagu/ShaguTweaks/commit/acf1e5dd99800f1b53a74f6a3e7a92d08678d5b0

**Comment by geojak** [comment]
Just to let you kmow. Also used to happen in twow hateforge quarry new trash items. Same error. Not sure if still in the most recent version thoguth
