### ISSUE TITLE
Conflicts with other nameplate addons

### ISSUE THREAD

**Issue by nullfoxh** [shagu/ShaguTweaks#39]
A user on the TBC Addons 2.4.3 discord was having issues using ShaguTweaks combined with the nameplate addons NotPlater and PlateBuffer.

I took a quick look and saw a couple potential issues. I'm busy so here's the screenshots of the convo, sorry.

![ss](https://user-images.githubusercontent.com/12772977/234929598-4d3d0337-301d-4e88-9433-b8b229523cdb.png)
![ss2](https://user-images.githubusercontent.com/12772977/234929683-acf53def-9bf1-48ce-87cd-396ddd95e84c.png)

In the latter snippet oldUpdate() is being called, when it should be oldShow().
It's also not passing the reference of the frame to the old function.

**Comment by shagu** [comment]
Thank you. Fixed via: https://github.com/shagu/ShaguTweaks/commit/91f561d8e476738e5d0d43208fd3bfcbd6121234
