### ISSUE TITLE
Latency indicator

### ISSUE THREAD

**Issue by burner1024** [shagu/ShaguTweaks#40]
Latency indicator is not visible when using reduced action bar size. Would be good to keep it somewhere on screen or provide a replacement.

**Comment by shagu** [comment]
Hi, thanks for you suggestion.

I understand that you might need it, but I personally don't. Please understand that I have similar requests for the micro-bar and the bag-bar. Now if I follow all those requests, the actionbar wouldn't be reduced anymore at all.

Maybe it's something that https://github.com/gryllsAddons/ShaguTweaks-mods would be interested in.
