### ISSUE TITLE
[TBC][Bug][Taint] - equip-compare module conflict

### ISSUE THREAD

**Issue by Sattva-108** [shagu/ShaguTweaks#42]
Currently IF you are warrior AND don't have shields equipped:
By using next macro - you get **Blocked Action** error.
```lua
/startattack
/cast [equipped:Shields, stance:1/2] Shield Bash; [noequipped:Shields, stance:1/2] Berserker Stance; Pummel
```

Taint Log Error:
```lua
7/8 06:10:28.661  Execution tainted by ShaguTweaks-tbc while reading CombatLogQuickButtonFrame_Custom - Interface\FrameXML\FloatingChatFrame.lua:689 FCF_OnUpdate()
7/8 06:10:28.661      UIParent:OnUpdate()
7/8 06:10:28.661  An action was blocked because of taint from ShaguTweaks-tbc - CastSpellByName()
7/8 06:10:28.661      Interface\FrameXML\ChatFrame.lua:819 ?()
7/8 06:10:28.661      Interface\FrameXML\ChatFrame.lua:3032 ChatEdit_ParseText()
7/8 06:10:28.661      Interface\FrameXML\ChatFrame.lua:2770 ChatEdit_SendText()
7/8 06:10:28.661      Interface\FrameXML\ChatFrame.lua:1921
7/8 06:10:28.661      UseAction()
7/8 06:10:28.661      Interface\FrameXML\SecureTemplates.lua:266 SecureActionButton_OnClick()
7/8 06:10:28.661      BonusActionButton6:OnClick()
```

Addon's active: **ShaguTweaks**, ACP, BugSack, BugGrabber, !Compatibility, !DebugTools

https://github.com/shagu/ShaguTweaks/assets/74269253/280a96ad-9b0e-4fe0-84d8-dbd758f7af3a

**Comment by Sattva-108** [comment]
Originally found and reported by: Cryptie. [**TBC 2.4.3 discord message link**](https://discord.com/channels/700662901358461028/700681162225352754/1126187272023318598)<br>
![reportsource](https://github.com/shagu/ShaguTweaks/assets/74269253/9b069d6f-20af-4e7a-93a0-9ba0c49aa572)

i found **solution** for him:
```txt
try to go in shagutweaks-tbc.toc 
and find line : mods\equip-compare.lua
then just put something before that line example: --mods\equip-compare.lua

tell me if it fixes. this is not gonna break anything,
 as this is a mod only for vanilla, but somehow it gets loaded and conflicts, at least for me
```

As he said it fixed it for him. 
Not sure what's the problem, i tried to comment every `CastSpellByName`, but that didn't do the job.
So i just disabled every file in toc one by one
 and found conflicting **mods\equip-compare.lua**

**Comment by shagu** [comment]
Thank you for this perfect bugreport. I won't have time today but will look into it as soon as possible.

**Comment by shagu** [comment]
The module was always touching global variables - even if not enabled. Could you please try again with the latest version?
I think it should be fixed via: https://github.com/shagu/ShaguTweaks/commit/cd8647c2015b5206b5ef1994aa55e88cc76cc902

**Comment by Sattva-108** [comment]
Works perfect for me, thanks! 
I also tagged guy who reported in discord, for him to try. 
Thank you for quick fix ^^
