### ISSUE TITLE
[Feature Request] Detect/Show Target Buffs

### ISSUE THREAD

**Issue by craigdbarber** [shagu/ShaguTweaks#50]
Currently unit frames do not display buffs on enemy targets. The request is to add a feature similar to pfUI's: [UnitFrames -> General -> Detect Enemy Buffs] which allows detection and display of enemy buffs on target unit frames. This would cater to those of us who would prefer to retain the Blizzlike UI look and feel, but still wish to be able to view enemy buffs.

**Comment by shagu** [comment]
Sorry, I have no plans to add this
