### ISSUE TITLE
Visual bug with world map

### ISSUE THREAD

**Issue by VanillaUI** [shagu/ShaguTweaks#52]
Turtle WOW, Latest version of ShaguTweaks.
Not so important, but maybe u will fix this in future (hide "World Map" text or move it to header (1)
![WoWScrnShot_100923_224135](https://github.com/shagu/ShaguTweaks/assets/146347755/5abead01-a68c-4716-9c81-8eb2ea2849a6)

**Comment by shagu** [comment]
Fixed via https://github.com/shagu/ShaguTweaks/commit/75f0a3eb7c7fae07a6b6778e1b99d23eb7d7c012
