### ISSUE TITLE
Sometimes show nonsence debuff numbers.

### ISSUE THREAD

**Issue by Griffithfalcon** [shagu/ShaguTweaks#55]
For example u open with cheap shot - shiwing 4 secs, u hit and deuff it with cripling poison and cheap shot again show 4 seconds but in reality there is like 2 seconds left...

**Comment by shagu** [comment]
It's guessing as good as it can based on the combat log and incomplete API we got in 1.12.
I don't know how to improve it further in a meaningful way. If you're interested and have ideas, here's the code that guesses debuff timers: https://github.com/shagu/ShaguTweaks/blob/master/libs/libdebuff.lua
