### ISSUE TITLE
Clock for TBC

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguTweaks#6]
The default TBC clock is kind of small, with ShaguTweaks I can change the font size of the clock.

Can you activate it for TBC too please?

**Comment by shagu** [comment]
No. TBC already has a clock. This addon is not here to replace UI elements to make them look different, it's the opposite.

Here's the 2.4.3 UI Source you can read about how frames are called: <https://github.com/tekkub/wow-ui-source/tree/2.4.3>
You can manipuate on your own, by doing your own addon or via macros:
```
/run TimeManagerClockButton:SetScale(1.2)
```
