### ISSUE TITLE
Flagging as a virus

### ISSUE THREAD

**Issue by Jyrabun** [shagu/ShaguTweaks#60]
Hello your mod/tweak flags itself as a virus specifrically either a PUP or a unwanted behavior. while i have allowed these  they still flag constantly. i am guessing due to this being an injector but when i try to quarantine the tweaked wow.exe does not work. Dont know if you already knew about this

**Comment by shagu** [comment]
This is an addon and not a client modification. I assume you're talking about vanilla-tweaks, which can be found here: https://github.com/brndd/vanilla-tweaks

**Comment by Jyrabun** [comment]
my bad
________________________________
