### ISSUE TITLE
[Feature Request] ChatTimestamps

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguTweaks#61]
Sorry if this was asked before, I would like to ask for adding an option to show chat timestamps into ShaguTweaks, like this addon - https://github.com/wbb1977/ChatTimestamps

Thank you

**Comment by shagu** [comment]
Hi, Thanks for your request, but I don't plan to add more features to this addon. 

ShaguTweaks isn't meant to replace every addon out there. I prefer to keep it simple and only contain what I consider the most important parts of later WoW versions, that aren't existing in our old vanilla clients.

I also don't want to make the same mistake again that I already did with pfUI, building a configuration nightmare by implementing every single request somebody has.

You could try on: https://github.com/GryllsAddons/ShaguTweaks-mods

Cheers,
Shagu

**Comment by FrostShock** [comment]
Thank you, ShaguTweaks-mods includes Chat Timestamps, that's really great!
