### ISSUE TITLE
[Feature Request] Quest Levels

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguTweaks#62]
Sorry if this was asked before too, but I would like to ask for adding an option to show quest levels in the Quest Log, like EQL3 is doing.

Thank you

**Comment by shagu** [comment]
Hi, Thanks for your request, but I don't plan to add more features to this addon. 

ShaguTweaks isn't meant to replace every addon out there. I prefer to keep it simple and only contain what I consider the most important parts of later WoW versions, that aren't existing in our old vanilla clients.

I also don't want to make the same mistake again that I already did with pfUI, building a configuration nightmare by implementing every single request somebody has.

You could try on: https://github.com/GryllsAddons/ShaguTweaks-mods

Cheers,
Shagu

**Comment by FrostShock** [comment]
Sorry for the late reply, I just found that pfQuest has the option to show quest levels, and that's great!
