### ISSUE TITLE
Unit Frame Class Colors

### ISSUE THREAD

**Issue by WuVenus** [shagu/ShaguTweaks#63]
Unit Frame Class Colors How to cancel Team color!!

Leave only the player with the target unit frame color
![image](https://github.com/shagu/ShaguTweaks/assets/144596429/a1c767bf-51f8-4c96-819e-0f6e21260f08)

**Comment by shagu** [comment]
delete these lines:
https://github.com/shagu/ShaguTweaks/blob/master/mods/unitframes-classcolor.lua#L69-L74

**Comment by WuVenus** [comment]
I deleted the part where he turned gray!!

**Comment by WuVenus** [comment]
ok nice Thank you very much for your help <3
