### ISSUE TITLE
Feature request: a sub-menu for custom options

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguTweaks#7]
As ShaguTweaks is designed as an AddOn for those who don't want to use any AddOns at all, some (like me) are interested to add more functionality, in order to reduce the number of other addons they are using.

I would like to place a request for adding a sub-menu containing "Lorem Ipsum" options, for custom options that players can define later

And, if possible, some indications about how to integrate more modules.

In my case, I would like to add options for removing Gryphons (from actionbars) and to add Chat Timestamps and [AuctionSearchTimer](https://github.com/EinBaum/AuctionSearchTimer) - and maybe Corpse Info

Also to change the ink of the health points number to white - and to delete the percentage %.

Thanks

**Comment by shagu** [comment]
I don't understand. I should code something for those who want to code?

**Comment by shagu** [comment]
https://github.com/shagu/ShaguTweaks/commit/81efaea6a9d7aa49820a287b8e4aa5e03d3ef43d

**Comment by shagu** [comment]
Based on your input:
The latest version now has:
- an option to hide gryphons
- an option to disable health colors
- player coordinates on worldmap

The GUI also changed a little bit and now offers categories. 
You can set a category for your own modules now. Entries without a category will be listed under "General".
