### ISSUE TITLE
Potential strsplit() errors in libs\libpredict.lua

### ISSUE THREAD

**Issue by fondlez** [shagu/ShaguTweaks#80]
Lines 59 and 100 of `libs\libpredict.lua` use a `strsplit()` function, but there is no local declaration for it or no clear indicator it should be present in the global environment.

**Comment by shagu** [comment]
Thank you, it's now fixed via: https://github.com/shagu/ShaguTweaks/commit/ca1acd64ef24732acc82af5850bba0c3d044f683
