### ISSUE TITLE
Doesn't work, pls Help me

### ISSUE THREAD

**Issue by aaascension** [shagu/ShaguTweaks#81]
Hello Shagu, please help me, your Shagu Tweaks addon doesn't work for me. I did everything according to the instructions, I'm attaching a screenshot with an error in the chat, I'm playing Vanilla Hardcore
![Безымянный](https://github.com/user-attachments/assets/77639d47-701d-4b80-80ac-74de9f10af2e)

**Comment by shagu** [comment]
Hello,
The addon is made for vanilla (1.12) which is the client from 2006. It does not work on classic (1.14+) which is blizzards remake from 2019.
