### ISSUE TITLE
Enemy cast bar is duplicated on other enemies

### ISSUE THREAD

**Issue by burner1024** [shagu/ShaguTweaks#9]
First off, big thank you for this addon. It's great, and hopefully it will continue to evolve and add more QoL features.

Now, to the bug: see screenshot. 2 identical mobs, one is aggroed and casting, the other one is just standing there. However, cast bars are drawn for both units.
![Captura de pantalla de 2021-12-30 02-48-55](https://user-images.githubusercontent.com/1279852/147698585-26d04415-7aa6-440d-8419-e387a0a467fa.png)

(Also, an unrelated question: is there a way to change font/font color for the nameplates to another, or WoW default one? I find the default one quite hard to read.)

**Comment by shagu** [comment]
Enemycastbars are done by reading the combat log. The combat log does not contain unit IDs, so the addon only knows the name of the mob, and therefore adds a castbar to every mob that has the name.

> is there a way to change font/font color for the nameplates to another, or WoW default one? I find the default one quite hard to read.

pfUI already gained that option, I'll add it to the ShaguPlates in the next update.

PS: You picked the wrong repository, your question is about ShaguPlates, not ShaguTweaks.

**Comment by burner1024** [comment]
Oops, sorry.
